language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make publish github
env:
  global:
    secure: "He2B3HFeOGmNq3/M2+2uDovsbzbWCveX4/WiQIomoQw9pEtj69uiu+SBh025cQjUGyl2B+f5pYlv6C5XO7nJejPirkiZRu0nk1/iGN2m/XhfqoCIDRIPAANt67vGsml484hHseuIsXhAfER3Z9TBNT5rKNZr2wRx+JmxcCD3x6ahBCx+OpkaI5VOrDB88rxYyIisx9qjGBKnOP8hFT2KN7MOmKlfXseOZfgcxKusMyvlc+8+I+z14YCeRO6AdYhqz8XcQ3eogs2GO7UGIe76IHuAp8gTI2969gS2ZMVlQ1zZdSVkO7KItfUHUDUe5uMqal/4fFTzOW7+7guJ8s8cKiaiJ46koOByGsZmPAcerLxmCazRvXim8zRHQwX1eBC5g+ASRzqEauXaBEk/4Sw0X+popFKh0tNGrFS+xh17PUdE+WeL4seLUzBIV1cGtwQehCgDQ0sH4NGhiaYqZk5JKUe1v+A2sQd7u7YypOrIxyETzMA+ctV21fz/NiqvHsAhKBXIvj666rQMKffTS3ECsxhFR9o8DYckpGccdlz23uCUkZDwbFkEqMa0ar9ISk0H8tlcJiqzbVy+O0SUOKDj6FEyv7L+dGLVZ0gzLG22eWv56MtDoOesRAVgeg2TjT7SfTGGQXL+APBEDf69BevgWx2VKsxxWmQKiBZ0Wxr071U=" 
